config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :todos
  post 'todos/reactjson' => 'todos#reactjson'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

    validates :item, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :update, :destroy]
    def index

    end
    def new
        @todo = Todo.new
    end

    def edit
        @todo = Todo.find(params[:id])
    end


    def create
        @todo = Todo.new(todo_params)
        if @todo.save
            flash[:notice] = "¡Tarea agregada!"
            redirect_to root_path

        else
            flash[:warning] = "Trata de nuevo, hubo un error."
            redirect_to root_path
        end
    end

    def update
        @todo = Todo.find(params[:id])

        if @todo.update(todo_params)
            redirect_to root_path
        else
            redirect_to root_path
        end
    end

    def show

    end
    def reactjson
      @todo = Todo.find(params[:id])

      if @todo.update(todo_params)
          redirect_to todos_path
      else
          redirect_to root_path
      end
    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to root_path
    end
    def set_todo
      @todo = Todo.find(params[:id])
    end


    private
    def todo_params
        params.require(:todo).permit(:item, :options => {})
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @todo = Todo.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/24eab6b1ca.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'welcome/notification'%>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with scope: @todo, url: todos_path do |f|%>
    <%= f.label "Add Your Pending Task", class: "label"%>
    <%= f.text_field :item, class: "input", placeholder: "Standup Meetings"%>
    <br>
    <%= f.label "Options", class: "label"%>
    <%= f.fields :options do |c| %>
      <%= c.text_field :cascoxs, class: "input", placeholder: "option" %>
    <% end %>
    <br>
    <%= f.submit "Add Task", class: "button is-danger is-fullwidth"%>
<% end %>

app/views/todos/edit.html.erb
<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<%= Todo.all().as_json %>

app/views/welcome/_form.html.erb
<%= form_with scope: @todo, url: todos_path do |f|%>
    <%= f.label "Add Your Pending Task", class: "label"%>
    <%= f.text_field :item, class: "input", placeholder: "Standup Meetings"%>
    <br>
    <%= f.submit "Add Task", class: "button is-danger is-fullwidth"%>
<% end %>
<%= react_component("CustomForm", { greeting: "Hello from react-rails.", todos: Todo.all().as_json}) %>

app/views/welcome/_notification.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success')%>
      new Noty({
          type: '<%= type %>',
          layout: 'topCenter',
          theme: 'metroui',
          text: '<%= value %>'
      }).show();
    <% end %>
  </script>
<% end %>

app/views/welcome/index.html.erb
<section class="hero is-primary is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-6-table is-6-desktop is-6widescreen">
          <div class="box">
            <div class="field has-text-centered">
              <strong>Have something Do Do?</strong><br>
              <small>Enter an task to do below.</small>
            </div>

<div class="columns">
 <div class="column ">
    <strong>Your To Do List</strong> <br>
    <ol class="list is-hoverable">
        <% @todo.each do |t| %>
          <li class = "list-item">
            <%= t.item %>
            <%= t.options %>
              <%= link_to '', edit_todo_path(t) , class:"fas fa-edit"%>
              <%= link_to '', t, method: :delete, class: "fas fa-trash" %>

          </li>
        <% end %>
    </ol>

  </div>
  <div class="column">
      <%= render 'form' %>
  </div>

</div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>